### PR TITLE
Keep GitHub Actions up to date with GitHub's Dependabot

### PR DESCRIPTION
**Pull request by cclauss**
### Summary

Keep GitHub Actions up to date with GitHub's Dependabot.

### Details and comments

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

### CODE REVIEW

**Review by blakejohnson — APPROVED** [review]
Seems like good practice. Thanks for contributing this change.

**Comment by blakejohnson** [comment]
Trying to add the "no-reno" label to see if that will make the checks happy.

**Comment by cclauss** [comment]
Approving the workflow run is required.

**Comment by cclauss** [comment]
Generated:
* #515

**Pull request merged**
